### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by timmwille**
what about MIT License?

### CODE REVIEW

**Comment by timmwille** [comment]
Looks like automatic merge is hanging in the air, I'll check

**Comment by TWille** [comment]
Looks like automatic merge is hanging in the air, I'll check

**Comment by TWille** [comment]
Looks like automatic merge is hanging in the air, I'll check

**Comment by TWille** [comment]
Looks like automatic merge is hanging in the air, I'll check

**Comment by TWille** [comment]
Looks like automatic merge is hanging in the air, I'll check

**Comment by timmwille** [comment]
now it looks ok ;)

**Pull request merged**
